minor change

diff --git a/.github/workflows/github-actions-apeiora-ows3.yml b/.github/workflows/github-actions-apeiora-ows3.yml
--- a/.github/workflows/github-actions-apeiora-ows3.yml
+++ b/.github/workflows/github-actions-apeiora-ows3.yml
@@ -12,8 +12,6 @@ jobs:
         uses: actions/checkout@v4
       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
       - run: echo "🖥️ The workflow is now ready to test the code on the runner."
-      - name: Print current directory
-        run: pwd
       - name: Check and install gardenctl
         run: |
           if ! command -v gardenctl &> /dev/null
@@ -74,16 +72,6 @@ jobs:
           else
             echo "kubelogin is already installed"
           fi
-      - name: Check and install make
-        run: |
-          if ! command -v make &> /dev/null
-          then
-            echo "make could not be found, installing..."
-            sudo apt-get update
-            sudo apt-get install -y make
-          else
-            echo "make is already installed"
-          fi
       - name: Check and install uuidgen and then set GCTL_SESSION_ID
         run: |
           if ! command -v uuidgen &> /dev/null
@@ -94,8 +82,17 @@ jobs:
           else
             echo "uuidgen is already installed"
           fi
-
           echo "GCTL_SESSION_ID=$(uuidgen)" >> $GITHUB_ENV
+      - name: Check and install make
+        run: |
+          if ! command -v make &> /dev/null
+          then
+            echo "make could not be found, installing..."
+            sudo apt-get update
+            sudo apt-get install -y make
+          else
+            echo "make is already installed"
+          fi
       - name: Apply K8 configs
         run:
           make k8
