minor change

diff --git a/.github/workflows/github-actions-apeiora-ows3.yml b/.github/workflows/github-actions-apeiora-ows3.yml
--- a/.github/workflows/github-actions-apeiora-ows3.yml
+++ b/.github/workflows/github-actions-apeiora-ows3.yml
@@ -36,6 +36,18 @@ jobs:
           else
             echo "gardenlogin is already installed"
           fi
+      - name: Check and install kubelogin
+        run: |
+          if ! command -v kubelogin &> /dev/null
+          then
+            echo "kubelogin could not be found, installing..."
+            curl -Lo kubelogin https://github.com/int128/kubelogin/releases/latest/download/kubelogin_linux_amd64.zip
+            unzip kubelogin_linux_amd64.zip
+            chmod +x kubelogin
+            sudo mv kubelogin /usr/local/bin/
+          else
+            echo "kubelogin is already installed"
+          fi
       - name: Check and install make
         run: |
           if ! command -v make &> /dev/null
