minor change

diff --git a/.github/workflows/github-actions-apeiora-ows3.yml b/.github/workflows/github-actions-apeiora-ows3.yml
--- a/.github/workflows/github-actions-apeiora-ows3.yml
+++ b/.github/workflows/github-actions-apeiora-ows3.yml
@@ -84,13 +84,13 @@ jobs:
             echo "kubelogin is already installed"
           fi
 
-          if ! command -v lynx &> /dev/null
-          then
-            echo "lynx could not be found, installing..."
-            sudo apt-get update && sudo apt-get install -y lynx
-          else
-            echo "lynx is already installed"
-          fi
+          # if ! command -v lynx &> /dev/null
+          # then
+          #   echo "lynx could not be found, installing..."
+          #   sudo apt-get update && sudo apt-get install -y lynx
+          # else
+          #   echo "lynx is already installed"
+          # fi
 
           make k8  
         env:
