minor change

diff --git a/.github/workflows/github-actions-apeiora-ows3.yml b/.github/workflows/github-actions-apeiora-ows3.yml
--- a/.github/workflows/github-actions-apeiora-ows3.yml
+++ b/.github/workflows/github-actions-apeiora-ows3.yml
@@ -10,31 +10,16 @@ jobs:
       - name: Check out repository code
         uses: actions/checkout@v4
       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-      - name: Check and install brew and gardenctl
+      - name: Check and install make
         run: |
-          if ! command -v brew &> /dev/null
+          if ! command -v make &> /dev/null
           then
-            echo "brew could not be found, installing..."
-            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-            (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
-            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
-            echo 'export PATH="${BREW_ROOT:-$HOME/linuxbrew/.linuxbrew}/bin:$PATH"' >> $GITHUB_ENV
-            echo 'export PATH="${BREW_ROOT:-$HOME/linuxbrew/.linuxbrew}/sbin:$PATH"' >> $GITHUB_ENV
+            echo "make could not be found, installing..."
+            sudo apt-get update
+            sudo apt-get install -y make
           else
-            echo "brew is already installed"
+            echo "make is already installed"
           fi
-
-          if ! command -v gardenctl &> /dev/null
-          then
-            echo "gardenctl could not be found, installing..."
-            brew install gardener/tap/gardenctl-v2
-            which gardenctl
-            echo 'export PATH="${GARDENCTL_ROOT:-$HOME/linuxbrew/.linuxbrew}/bin/gardenctl:$PATH"' >> $GITHUB_ENV
-            which gardenctl
-            echo $PATH
-          else
-            echo "gardenctl is already installed"
-          fi          
       - name: Check and install gardenlogin
         run: |
           if ! command -v gardenlogin &> /dev/null
@@ -95,30 +80,31 @@ jobs:
             echo "uuidgen is already installed"
           fi
           echo "GCTL_SESSION_ID=$(uuidgen)" >> $GITHUB_ENV
-      - name: Check and install make
+      - name: Check and install brew and gardenctl; publish afterwards
         run: |
-          if ! command -v make &> /dev/null
+          if ! command -v brew &> /dev/null
           then
-            echo "make could not be found, installing..."
-            sudo apt-get update
-            sudo apt-get install -y make
+            echo "brew could not be found, installing..."
+            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+            (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
+            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
+            echo 'export PATH="${BREW_ROOT:-$HOME/linuxbrew/.linuxbrew}/bin:$PATH"' >> $GITHUB_ENV
+            echo 'export PATH="${BREW_ROOT:-$HOME/linuxbrew/.linuxbrew}/sbin:$PATH"' >> $GITHUB_ENV
           else
-            echo "make is already installed"
+            echo "brew is already installed"
           fi
-      - name: Apply K8 configs
-        run: |
-          if ! command -v gardenctl-v2 &> /dev/null
+           if ! command -v gardenctl &> /dev/null
           then
-            echo "gardenctl could not be found"
-            echo $PATH
+            echo "gardenctl could not be found, installing..."
+            brew install gardener/tap/gardenctl-v2
+            echo 'export PATH="${GARDENCTL_ROOT:-$HOME/linuxbrew/.linuxbrew}/bin/gardenctl:$PATH"' >> $GITHUB_ENV
           else
             echo "gardenctl is already installed"
-            which gardenctl
-          fi 
-          # make k8
-        env:
-          GARDEN_OWS3_PATH: ${{ secrets.GARDEN_OWS3_PATH }}
-          K8_CLUSTER_PATH: ${{ secrets.K8_CLUSTER_PATH }}
+          fi
+          make k8  
+          env:
+            GARDEN_OWS3_PATH: ${{ secrets.GARDEN_OWS3_PATH }}
+            K8_CLUSTER_PATH: ${{ secrets.K8_CLUSTER_PATH }}
       # - name: Run tests using make
       #   run: make tmptest
       # - name: List files in the repository
