minor change

diff --git a/.github/workflows/github-actions-apeiora-ows3.yml b/.github/workflows/github-actions-apeiora-ows3.yml
--- a/.github/workflows/github-actions-apeiora-ows3.yml
+++ b/.github/workflows/github-actions-apeiora-ows3.yml
@@ -5,24 +5,31 @@ jobs:
   ApeiroRA-OWS3-GitHub-Actions:
     runs-on: ubuntu-latest
     steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub."
+      - run: echo "🎉 The job is running on a ${{ runner.os }} server and was automatically triggered by a ${{ github.event_name }} event."
       - run: echo "🔎 The name of the branch is ${{ github.ref }} and repository is ${{ github.repository }}."
       - name: Check out repository code
         uses: actions/checkout@v4
       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-      - run: echo "🖥️ The workflow is now ready to test the code on the runner."
-      - name: Check and install gardenctl
+      - name: Check and install brew and gardenctl
         run: |
+          if ! command -v brew &> /dev/null
+          then
+            echo "brew could not be found, installing..."
+            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+            BREW_ROOT="${BREW_ROOT:-$HOME/.linuxbrew}"
+            echo "export PATH=\"$BREW_ROOT/bin:\$PATH\"" >> $GITHUB_ENV
+            echo "export PATH=\"$BREW_ROOT/sbin:\$PATH\"" >> $GITHUB_ENV
+          else
+            echo "brew is already installed"
+          fi
+
           if ! command -v gardenctl &> /dev/null
           then
             echo "gardenctl could not be found, installing..."
-            curl -Lo gardenctl https://github.com/gardener/gardenctl/releases/latest/download/gardenctl-linux-amd64
-            chmod +x gardenctl
-            sudo mv gardenctl /usr/local/bin/
+            brew install gardener/tap/gardenctl-v2
           else
             echo "gardenctl is already installed"
-          fi
+          fi          
       - name: Check and install gardenlogin
         run: |
           if ! command -v gardenlogin &> /dev/null
