minor change

diff --git a/.github/workflows/github-actions-apeiora-ows3.yml b/.github/workflows/github-actions-apeiora-ows3.yml
--- a/.github/workflows/github-actions-apeiora-ows3.yml
+++ b/.github/workflows/github-actions-apeiora-ows3.yml
@@ -57,7 +57,7 @@ jobs:
           fi
           echo "GCTL_SESSION_ID=$(uuidgen)" >> $GITHUB_ENV
 
-      - name: Check and install brew, brew, kubelogin and gardenctl; publish afterwards
+      - name: Check and install brew, kubelogin and gardenctl; publish afterwards
         run: |
           if ! command -v brew &> /dev/null
           then
@@ -80,33 +80,32 @@ jobs:
             echo "gardenctl is already installed"
           fi
 
-          if ! command -v kubectl-krew &> /dev/null
-          then
-            echo "krew could not be found, installing..."
-            (
-              set -x; cd "$(mktemp -d)" &&
-              OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
-              ARCH="$(uname -m | sed 's/x86_64/amd64/' | sed 's/arm.*$/arm/')" &&
-              KREW="krew-${OS}_${ARCH}" &&
-              curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
-              tar zxvf "${KREW}.tar.gz" &&
-              ./"${KREW}" install krew
-            )
-            export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
-            echo 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"' >> $GITHUB_ENV
-          else
-            echo "krew is already installed"
-          fi
+          # if ! command -v kubectl-krew &> /dev/null
+          # then
+          #   echo "krew could not be found, installing..."
+          #   (
+          #     set -x; cd "$(mktemp -d)" &&
+          #     OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
+          #     ARCH="$(uname -m | sed 's/x86_64/amd64/' | sed 's/arm.*$/arm/')" &&
+          #     KREW="krew-${OS}_${ARCH}" &&
+          #     curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
+          #     tar zxvf "${KREW}.tar.gz" &&
+          #     ./"${KREW}" install krew
+          #   )
+          #   export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
+          #   echo 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"' >> $GITHUB_ENV
+          # else
+          #   echo "krew is already installed"
+          # fi
 
           if ! command -v kubelogin &> /dev/null
           then
             echo "kubelogin could not be found, installing..."
-            kubectl krew install oidc-login
+            brew install int128/kubelogin/kubelogin
           else
             echo "kubelogin is already installed"
           fi
 
-          oidc-login --version
           make k8  
         env:
             GARDEN_OWS3_PATH: ${{ secrets.GARDEN_OWS3_PATH }}
